from app import db
from app.models import City

CITY_NAMES = [
    # Major Metropolitan Cities
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Surat",
    "Jaipur",
    
    # Andhra Pradesh
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Tirupati",
    "Kakinada",
    "Rajahmundry",
    "Kadapa",
    "Anantapur",
    "Kurnool",
    "Eluru",
    "Ongole",
    "Nandyal",
    "Machilipatnam",
    "Adoni",
    "Tenali",
    "Chittoor",
    "Hindupur",
    "Proddatur",
    "Bhimavaram",
    
    # Arunachal Pradesh
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Tawang",
    "Ziro",
    "Bomdila",
    
    # Assam
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Karimganj",
    "Dhubri",
    "North Lakhimpur",
    "Goalpara",
    "Barpeta",
    "Sivasagar",
    
    # Bihar
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Munger",
    "Chapra",
    "Begusarai",
    "Katihar",
    "Sasaram",
    "Hajipur",
    "Dehri",
    "Siwan",
    "Motihari",
    "Nawada",
    "Bagaha",
    "Buxar",
    "Kishanganj",
    "Sitamarhi",
    "Jamalpur",
    "Jehanabad",
    "Aurangabad Bihar",
    
    # Chhattisgarh
    "Raipur",
    "Bhilai",
    "Bilaspur",
    "Korba",
    "Durg",
    "Rajnandgaon",
    "Jagdalpur",
    "Raigarh",
    "Ambikapur",
    "Mahasamund",
    "Dhamtari",
    "Chirmiri",
    "Bhatapara",
    
    # Goa
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Curchorem",
    
    # Gujarat
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Navsari",
    "Morbi",
    "Surendranagar",
    "Bharuch",
    "Mehsana",
    "Bhuj",
    "Porbandar",
    "Palanpur",
    "Valsad",
    "Vapi",
    "Gondal",
    "Veraval",
    "Godhra",
    "Patan",
    "Kalol",
    "Dahod",
    "Botad",
    "Amreli",
    "Deesa",
    "Jetpur",
    
    # Haryana
    "Faridabad",
    "Gurgaon",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
    "Bhiwani",
    "Sirsa",
    "Bahadurgarh",
    "Jind",
    "Thanesar",
    "Kaithal",
    "Rewari",
    "Palwal",
    "Pinjore",
    "Hansi",
    "Narnaul",
    "Fatehabad",
    "Gohana",
    "Tohana",
    
    # Himachal Pradesh
    "Shimla",
    "Dharamshala",
    "Solan",
    "Mandi",
    "Palampur",
    "Baddi",
    "Nahan",
    "Una",
    "Hamirpur",
    "Kullu",
    "Bilaspur HP",
    "Chamba",
    "Kangra",
    "Sundernagar",
    
    # Jharkhand
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Phusro",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar",
    "Chirkunda",
    
    # Karnataka
    "Bangalore",
    "Mysore",
    "Mangalore",
    "Hubli",
    "Dharwad",
    "Belgaum",
    "Gulbarga",
    "Davangere",
    "Bellary",
    "Bijapur",
    "Shimoga",
    "Tumkur",
    "Raichur",
    "Bidar",
    "Hospet",
    "Gadag-Betageri",
    "Robertsonpet",
    "Hassan",
    "Bhadravati",
    "Chitradurga",
    "Udupi",
    "Kolar",
    "Mandya",
    "Chikmagalur",
    "Gangavati",
    "Bagalkot",
    "Ranibennur",
    
    # Kerala
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Palakkad",
    "Alappuzha",
    "Malappuram",
    "Kannur",
    "Kottayam",
    "Kasaragod",
    "Thalassery",
    "Ponnani",
    "Vatakara",
    "Kanhangad",
    "Payyanur",
    "Koyilandy",
    "Parappanangadi",
    "Kalamassery",
    "Neyyattinkara",
    "Tanur",
    "Kayamkulam",
    "Thrippunithura",
    "Aluva",
    "Attingal",
    "Varkala",
    "Munnar",
    "Alleppey",
    "Wayanad",
    
    # Madhya Pradesh
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Murwara",
    "Singrauli",
    "Burhanpur",
    "Khandwa",
    "Morena",
    "Bhind",
    "Chhindwara",
    "Guna",
    "Shivpuri",
    "Vidisha",
    "Chhatarpur",
    "Damoh",
    "Mandsaur",
    "Khargone",
    "Neemuch",
    "Pithampur",
    "Hoshangabad",
    "Itarsi",
    "Sehore",
    "Betul",
    "Seoni",
    
    # Maharashtra
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Amravati",
    "Nanded",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Chandrapur",
    "Parbhani",
    "Jalgaon",
    "Bhusawal",
    "Navi Mumbai",
    "Panvel",
    "Sangli",
    "Malegaon",
    "Jalna",
    "Satara",
    "Beed",
    "Yavatmal",
    "Kamptee",
    "Gondia",
    "Barshi",
    "Achalpur",
    "Osmanabad",
    "Nandurbar",
    "Wardha",
    "Udgir",
    "Hinganghat",
    
    # Manipur
    "Imphal",
    "Thoubal",
    "Bishnupur",
    "Kakching",
    "Churachandpur",
    "Ukhrul",
    "Moreh",
    
    # Meghalaya
    "Shillong",
    "Tura",
    "Nongstoin",
    "Jowai",
    
    # Mizoram
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    
    # Nagaland
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    
    # Odisha
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Brahmapur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
    "Jeypore",
    "Bargarh",
    "Paradip",
    "Bhawanipatna",
    "Dhenkanal",
    "Barbil",
    "Kendrapara",
    "Sunabeda",
    "Rayagada",
    "Jatani",
    "Chhatrapur",
    "Byasanagar",
    "Konark",
    
    # Punjab
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Pathankot",
    "Hoshiarpur",
    "Batala",
    "Moga",
    "Malerkotla",
    "Khanna",
    "Phagwara",
    "Muktsar",
    "Barnala",
    "Rajpura",
    "Firozpur",
    "Kapurthala",
    "Zirakpur",
    "Kot Kapura",
    "Faridkot",
    "Sunam",
    "Gurdaspur",
    "Kharar",
    "Gobindgarh",
    "Mansa",
    "Malout",
    "Nabha",
    "Tarn Taran",
    "Jagraon",
    "Budhlada",
    "Rampura Phul",
    
    # Rajasthan
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Tonk",
    "Kishangarh",
    "Beawar",
    "Hanumangarh",
    "Sri Ganganagar",
    "Jhunjhunu",
    "Churu",
    "Barmer",
    "Sawai Madhopur",
    "Nagaur",
    "Makrana",
    "Sujangarh",
    "Sardarshahar",
    "Bundi",
    "Baran",
    "Jhalawar",
    "Mount Abu",
    "Pushkar",
    "Chittorgarh",
    "Banswara",
    "Dungarpur",
    "Pratapgarh",
    
    # Sikkim
    "Gangtok",
    "Namchi",
    "Gyalshing",
    "Mangan",
    "Rangpo",
    
    # Tamil Nadu
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Thanjavur",
    "Dindigul",
    "Ranipet",
    "Sivakasi",
    "Karur",
    "Udhagamandalam",
    "Hosur",
    "Nagercoil",
    "Kancheepuram",
    "Kumarapalayam",
    "Karaikkudi",
    "Neyveli",
    "Cuddalore",
    "Kumbakonam",
    "Tiruvannamalai",
    "Pollachi",
    "Rajapalayam",
    "Gudiyatham",
    "Pudukkottai",
    "Vaniyambadi",
    "Ambur",
    "Nagapattinam",
    "Ooty",
    "Kodaikanal",
    "Yercaud",
    
    # Telangana
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Khammam",
    "Karimnagar",
    "Ramagundam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Siddipet",
    "Miryalaguda",
    "Jagtial",
    "Mancherial",
    "Nirmal",
    "Kothagudem",
    "Bodhan",
    "Palwancha",
    "Mandamarri",
    "Koratla",
    "Sircilla",
    
    # Tripura
    "Agartala",
    "Dharmanagar",
    "Udaipur Tripura",
    "Kailasahar",
    "Belonia",
    "Khowai",
    
    # Uttar Pradesh
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Varanasi",
    "Meerut",
    "Allahabad",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Noida",
    "Firozabad",
    "Jhansi",
    "Muzaffarnagar",
    "Mathura",
    "Rampur",
    "Shahjahanpur",
    "Farrukhabad",
    "Maunath Bhanjan",
    "Hapur",
    "Ayodhya",
    "Etawah",
    "Mirzapur",
    "Bulandshahr",
    "Sambhal",
    "Amroha",
    "Hardoi",
    "Fatehpur",
    "Raebareli",
    "Orai",
    "Sitapur",
    "Bahraich",
    "Modinagar",
    "Unnao",
    "Jaunpur",
    "Lakhimpur",
    "Hathras",
    "Banda",
    "Pilibhit",
    "Barabanki",
    "Khurja",
    "Gonda",
    "Mainpuri",
    "Lalitpur",
    "Etah",
    "Deoria",
    "Ballia",
    "Basti",
    "Faizabad",
    "Sultanpur",
    "Shikohabad",
    "Azamgarh",
    "Ghazipur",
    "Chandausi",
    "Shamli",
    "Rae Bareli",
    
    # Uttarakhand
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Nainital",
    "Mussoorie",
    "Pithoragarh",
    "Almora",
    "Ranikhet",
    "Tehri",
    "Pauri",
    "Ramnagar",
    "Kotdwar",
    "Tanakpur",
    "Vikasnagar",
    "Sitarganj",
    "Manglaur",
    
    # West Bengal
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Bardhaman",
    "Malda",
    "Baharampur",
    "Habra",
    "Kharagpur",
    "Shantipur",
    "Dankuni",
    "Dhulian",
    "Ranaghat",
    "Haldia",
    "Raiganj",
    "Krishnanagar",
    "Nabadwip",
    "Medinipur",
    "Jalpaiguri",
    "Balurghat",
    "Basirhat",
    "Bankura",
    "Chakdaha",
    "Darjeeling",
    "Alipurduar",
    "Purulia",
    "Jangipur",
    "Bangaon",
    "Cooch Behar",
    
    # Union Territories
    "Chandigarh",
    "Pondicherry",
    "Port Blair",
    "Kavaratti",
    "Silvassa",
    "Daman",
    "Diu",
    "Dadra",
    "Jammu",
    "Srinagar",
    "Leh",
    "Ladakh",
    
    # Tourist & Hill Stations
    "Manali",
    "Bir Billing",
    "Coorg",
    "Dharamshala",
    "Goa",
    "Gokarna",
    "Hampi",
    "Khajuraho",
    "Ajanta",
    "Ellora",
    "Pushkar",
    "Ranthambore",
    "Jim Corbett",
    "Kaziranga",
    "Sundarbans",
    "Andaman and Nicobar Islands",
    "Lakshadweep",
    "Lonavala",
    "Mahabaleshwar",
]


def seed_cities() -> None:
    existing = {city.name for city in City.query.all()}
    new_cities = [City(name=name) for name in CITY_NAMES if name not in existing]

    if not new_cities:
        return

    db.session.bulk_save_objects(new_cities)
    db.session.commit()
