"""initial

Revision ID: fc1aca8ed8bb
Revises: 
Create Date: 2025-12-28 12:19:43.586302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1aca8ed8bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_brands_name'), ['name'], unique=True)

    op.create_table('cities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_provider_id'), ['provider_id'], unique=False)

    op.create_table('agencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=True),
    sa.Column('agency_name', sa.String(length=120), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('agency_phone', sa.String(length=20), nullable=True),
    sa.Column('agency_email', sa.String(length=120), nullable=True),
    sa.Column('gst_doc_url', sa.String(length=255), nullable=True),
    sa.Column('business_photo_url', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('bank_account_number', sa.String(length=20), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('bank_account_holder_name', sa.String(length=120), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_vehicles', sa.Integer(), nullable=True),
    sa.Column('total_bookings', sa.Integer(), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('catalog_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog_brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'name', name='uq_brand_model')
    )
    with op.batch_alter_table('catalog_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_models_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_models_name'), ['name'], unique=False)

    op.create_table('kyc_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_verified', sa.Boolean(), nullable=True),
    sa.Column('aadhaar_document_url', sa.String(length=255), nullable=True),
    sa.Column('driving_license_number', sa.String(length=20), nullable=True),
    sa.Column('dl_verified', sa.Boolean(), nullable=True),
    sa.Column('dl_document_url', sa.String(length=255), nullable=True),
    sa.Column('dl_expiry_date', sa.Date(), nullable=True),
    sa.Column('selfie_document_url', sa.String(length=255), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('pan_verified', sa.Boolean(), nullable=True),
    sa.Column('address_proof_type', sa.String(length=50), nullable=True),
    sa.Column('address_proof_url', sa.String(length=255), nullable=True),
    sa.Column('address_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('documents_uploaded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('password_reset_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_requests_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('avatar_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('vin', sa.String(length=100), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('seating_capacity', sa.Integer(), nullable=True),
    sa.Column('displacement', sa.String(length=50), nullable=True),
    sa.Column('top_speed', sa.String(length=50), nullable=True),
    sa.Column('fuel_capacity', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('late_fee_per_hr', sa.Float(), nullable=True),
    sa.Column('excess_per_km', sa.Float(), nullable=True),
    sa.Column('timings', sa.String(length=100), nullable=True),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('weekly_rate', sa.Float(), nullable=True),
    sa.Column('monthly_rate', sa.Float(), nullable=True),
    sa.Column('security_deposit', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('registration_expiry', sa.Date(), nullable=True),
    sa.Column('pollution_certificate_number', sa.String(length=100), nullable=True),
    sa.Column('pollution_expiry', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('dropoff_location', sa.String(length=255), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('number_of_days', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('security_deposit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('odometer_start', sa.Integer(), nullable=True),
    sa.Column('odometer_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_url', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('contact', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('vehicle_images')
    op.drop_table('vehicle_documents')
    op.drop_table('bookings')
    op.drop_table('vehicles')
    op.drop_table('user_roles')
    op.drop_table('profiles')
    with op.batch_alter_table('password_reset_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_requests_user_id'))

    op.drop_table('password_reset_requests')
    op.drop_table('kyc_verifications')
    with op.batch_alter_table('catalog_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_models_name'))
        batch_op.drop_index(batch_op.f('ix_catalog_models_brand_id'))

    op.drop_table('catalog_models')
    op.drop_table('agencies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_provider_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('cities')
    with op.batch_alter_table('catalog_brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_brands_name'))

    op.drop_table('catalog_brands')
    # ### end Alembic commands ###
